spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-206-38-187.compute-1.amazonaws.com/d8ut4rughugiih
    username: cgfyszbcrgjete
    password: e5fc7c397ca5974b69e56871150e7620dcbd73bd4f309cb8cdaa2be66fe986f0
    hikari:
      maximum-pool-size: 6


  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      platform: postgres

jwt:
  secret-key: ghkddlsrb_cjswo_gjgnswp_qkqh0ajdcjddl
  # 30 days
  token.expired-time-ms: 2592000000


